#pragma once
#ifndef chaoGL
#define chaoGL
#define GLM_SWIZZLE

#include "root_directory.h" // This is a configuration file generated by CMake.

#include <GLFW/glfw3.h>
#include <glad/glad.h>

#include <stb_image.h>
#include <File/filesystem.h>
#include <glm.hpp>
#include <gtc/matrix_transform.hpp>
#include <gtc/type_ptr.hpp>

#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>

#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>

#include <Render/Render.h>
#include <Object/Transform.h>

using namespace glm;

#endif // !chaoGL

